
variables:
    GIT_SUBMODULE_STRATEGY: recursive

release:
  image: python:latest
  before_script:
      - pip install anybadge
  stage: build
  script:
    # create badges (use version from python compiled spec)
    - php_version_var=`sed -n "s/__version__ = '\(.*\)/\1/p" < . examples/php/lbsnstructure/version/version.py`
    - python_version_var=`sed -n "s/__version__ = '\(.*\)/\1/p" < . examples/python/lbsnstructure/version.py`
    - version_var=`sed -n "s/__version__ = '\(.*\)/\1/p" < . version/version.py`
    - anybadge -l php --value="${version_var::-1}" --file=version.svg --color=green
    - anybadge -l php --value="${php_version_var::-1}" --file=php-version.svg --color=blue
    - anybadge -l python --value="${python_version_var::-1}" --file=python-version.svg --color=yellow
    - anybadge -l pipeline --value=passing --file=pipeline.svg passing=green failing=red
  artifacts:
    paths:
      - php-version.svg
      - python-version.svg
      - version.svg
      - pipeline.svg
  only:
  - master

pages:
  stage: deploy
  image: python:alpine
  before_script:
      - pip install mkdocs
      # Add your custom theme if not inside a theme_dir
      # (https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)
      # - pip install mkdocs-material
  script:
    # create folder public for badges
    - mkdir .public
    - cp php-version.svg .public
    - cp python-version.svg .public
    - cp version.svg .public
    - cp pipeline.svg .public
    - mv .public public
    # build docs
    - mkdocs build
    - mv site public
    - mv public/site public/docs
  artifacts:
    name: pages
    paths:
    - public
  only:
  - master

