
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # relative namespace of project
  REL_NAMESPACE: "/structure/protobuf/"

pages:
  image: python:latest
  before_script:
      - pip install anybadge
  stage: build
  script:
    # create badges (use version from python compiled spec)
    - php_version_var=`sed -n "s/__version__ = '\(.*\)/\1/p" < . examples/php/version/version.py`
    - python_version_var=`sed -n "s/__version__ = '\(.*\)/\1/p" < . examples/python/src/lbsnstructure/version.py`
    - version_var=`sed -n "s/__version__ = '\(.*\)/\1/p" < . version/version.py`
    - anybadge -l version --value="${version_var::-1}" --file=version.svg --color=green
    - anybadge -l php --value="${php_version_var::-1}" --file=php-version.svg --color=#1182C3
    - anybadge -l python --value="${python_version_var::-1}" --file=python-version.svg --color=yellow
    - anybadge -l pipeline --value=passing --file=pipeline.svg passing=green failing=red
    # create folder public for badges
    - mkdir -p public/
    - cp *.svg public/
  artifacts:
    name: pages
    paths:
    - public
  only:
  - master

