site_name: LBSN Structure Concept
site_url: https://lbsn.gitlab.vgiscience.de/concept
site_author: Alexander Dunkel, Marc Löchner, Filip Krumpe
copyright: MIT License, Copyright (c) 2019 Alexander Dunkel, Marc Löchner, Filip Krumpe
site_dir: docs
nav:
    - 'Introduction': 'index.md'
    - 'Structure Overview': 'structure-overview.md'
    - 'About': 'about.md'