site_name: LBSN Structure Concept
site_url: https://lbsn.vgiscience.org/concept/docs
site_author: Alexander Dunkel, Marc Löchner, Filip Krumpe
copyright: MIT License, Copyright (c) 2019 Alexander Dunkel, Marc Löchner, Filip Krumpe
site_dir: site
nav:
    - 'Introduction': 'index.md'
    - User Guide:
        - 'Structure Overview': 'structure-overview.md'
        - 'Service Mappings': 'service_function_overview.md'
        - 'Privacy & Anonymization': 'security-anonymization.md'
        - 'Example queries': 'example-queries.md'
    - 'About': 'about.md'